# Generated by Django 3.0 on 2025-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20250707_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
