# Generated by Django 3.0 on 2025-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_quizscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='taken_on',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='is_perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
